default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  username: postgres  # Change it to your username
  password: postgres    # Change it to your password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 5000

development:
  <<: *default
  database: file_uploader_development

test:
  <<: *default
  database: file_uploader_test

production:
  <<: *default
  database: file_uploader_production
